steps:
  - id: "Update GCS Bucket"
    name: "gcr.io/cloud-builders/gsutil"
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod +x ./updatebucket.sh
      ./updatebucket.sh $PROJECT_NUMBER

options:
  logStreamingOption: STREAM_ON



