steps:
  - id: "Update GCS Bucket"
    name: "gcr.io/cloud-builders/gsutil"
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod +x ./updatebucket.sh
      ./updatebucket.sh $PROJECT_NUMBER

  - id: "Invalidate Cloud CDN"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud compute url-maps invalidate-cdn-cache example-lb --path "/*"

options:
  logStreamingOption: STREAM_ON



