name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Login GH CLI
        with:
          token: ${{ secrets.GH_TOKEN }}
        run: echo $token >>  key \
          gh auth login --with-token < key \
          gh auth status

      - name: Use gcloud CLI
        run: gcloud info